### ISSUE TITLE
Error while training 

### ISSUE THREAD

**Issue by Stacey940** [mtbikerj/RasaDocker#1] opened 2018-05-03 20:35 UTC
Hi , thanks for the great tutorial , I am getting below error when I try to run command to train the nlu

D:\ai\rasa_nlu\RasaDocker\nlu>python -m rasa_nlu.train -c config.json 

usage: train.py [-h] [-o PATH] (-d DATA | -u URL) -c CONFIG [-t NUM_THREADS]
                [--project PROJECT] [--fixed_model_name FIXED_MODEL_NAME]
                [--storage STORAGE] [--debug] [-v]
train.py: error: one of the arguments -d/--data -u/--url is required

**Comment by mtbikerj** [comment] 2018-07-11 15:25
Thanks.  This might have to do with a newer version of Rasa that I haven't tested yet.  I'll take a look and push any fix that I find.

**Comment by mtbikerj** [comment] 2018-07-11 15:55
Yes, I can confirm the version 0.12.0 of rasa broke the tutorial because the data file can no longer be set inside the config.json file.  The training issue from the command line can be resolved by changing your command to:

D:\ai\rasa_nlu\RasaDocker\nlu>python -m rase_nlu.train -c config.json -d data/train.md

I will work on updating the dockerfiles in this repository to fix the issue.

**Comment by mtbikerj** [comment] 2018-07-13 12:43
Fixed Dockerfile.nlu in all branches for breaking change due to rasa version 0.12.0

**Closed as completed by mtbikerj** 2018-07-13 12:43 UTC
